#include "spp_gsp_headgate_dynboost_phase.h"

#define SPP_BWC_VARIANT_TAG "BWC_GSP_HEADGATE_DYNBOOST_PHASE"
#define SPP_BWC_ENABLE_GLOBAL_GSP 1
#define SPP_BWC_ENABLE_TIERED_GLOBAL 1
#define SPP_BWC_ENABLE_SIG_UTIL 1
#define SPP_BWC_ENABLE_HEADGATE 1
#define SPP_BWC_ENABLE_HEADGATE_STREAMING_KEEP_TAIL 1
#define SPP_BWC_ENABLE_HEADGATE_DYNBOOST 1
#define SPP_BWC_ENABLE_HEADGATE_PHASEROTATE 1
#define spp_bwc spp_gsp_headgate_dynboost_phase
#include "../spp_bwc/spp_bwc_impl.inc"
#undef spp_bwc
#undef SPP_BWC_ENABLE_HEADGATE_PHASEROTATE
#undef SPP_BWC_ENABLE_HEADGATE_DYNBOOST
#undef SPP_BWC_ENABLE_HEADGATE_STREAMING_KEEP_TAIL
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_VARIANT_TAG
