#include "spp_gsp_headgate_taildemote.h"

#define SPP_BWC_VARIANT_TAG "BWC_GSP_HEADGATE_TAILDEMOTE"
#define SPP_BWC_ENABLE_GLOBAL_GSP 1
#define SPP_BWC_ENABLE_TIERED_GLOBAL 1
#define SPP_BWC_ENABLE_SIG_UTIL 1
#define SPP_BWC_ENABLE_HEADGATE 1
#define SPP_BWC_HEADGATE_KEEP_CANDIDATES 2
#define SPP_BWC_ENABLE_HEADGATE_TAIL_DEMOTE 1
#define spp_bwc spp_gsp_headgate_taildemote
#include "../spp_bwc/spp_bwc_impl.inc"
#undef spp_bwc
#undef SPP_BWC_ENABLE_HEADGATE_TAIL_DEMOTE
#undef SPP_BWC_HEADGATE_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_VARIANT_TAG
