#include "spp_gsp_headgate_l2qual.h"

#define SPP_BWC_VARIANT_TAG "BWC_GSP_HEADGATE_L2QUAL"
#define SPP_BWC_ENABLE_GLOBAL_GSP 1
#define SPP_BWC_ENABLE_TIERED_GLOBAL 1
#define SPP_BWC_ENABLE_SIG_UTIL 1
#define SPP_BWC_ENABLE_HEADGATE 1
#define SPP_BWC_HEADGATE_KEEP_CANDIDATES 2
#define SPP_BWC_ENABLE_HEADGATE_L2QUAL 1
#define SPP_BWC_HEADGATE_L2QUAL_MID_SCORE_THRESHOLD 0
#define SPP_BWC_HEADGATE_L2QUAL_TAIL_SCORE_THRESHOLD 4
#define spp_bwc spp_gsp_headgate_l2qual
#include "../spp_bwc/spp_bwc_impl.inc"
#undef spp_bwc
#undef SPP_BWC_HEADGATE_L2QUAL_TAIL_SCORE_THRESHOLD
#undef SPP_BWC_HEADGATE_L2QUAL_MID_SCORE_THRESHOLD
#undef SPP_BWC_ENABLE_HEADGATE_L2QUAL
#undef SPP_BWC_HEADGATE_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_VARIANT_TAG
