#include "spp_gsp_headgate_tierkeep.h"

#define SPP_BWC_VARIANT_TAG "BWC_GSP_HEADGATE_TIERKEEP"
#define SPP_BWC_ENABLE_GLOBAL_GSP 1
#define SPP_BWC_ENABLE_TIERED_GLOBAL 1
#define SPP_BWC_ENABLE_SIG_UTIL 1
#define SPP_BWC_ENABLE_HEADGATE 1
#define SPP_BWC_HEADGATE_KEEP_CANDIDATES 2
#define SPP_BWC_ENABLE_HEADGATE_TIERKEEP 1
#define SPP_BWC_HEADGATE_LIGHT_KEEP_CANDIDATES 3
#define spp_bwc spp_gsp_headgate_tierkeep
#include "../spp_bwc/spp_bwc_impl.inc"
#undef spp_bwc
#undef SPP_BWC_HEADGATE_LIGHT_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE_TIERKEEP
#undef SPP_BWC_HEADGATE_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_VARIANT_TAG
