#ifndef SPP_GSP_HEADGATE_FILLBOOST_H
#define SPP_GSP_HEADGATE_FILLBOOST_H

#ifdef SPP_BWC_H
#define SPP_GSP_HEADGATE_FILLBOOST_RESTORE_SPP_BWC_H 1
#undef SPP_BWC_H
#endif

#undef SPP_BWC_VARIANT_TAG
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_HEADGATE_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE_STREAMING_BOOST
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_PF_THRESHOLD
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_FILL_THRESHOLD
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_ISSUE_PERIOD

#define SPP_BWC_VARIANT_TAG "BWC_GSP_HEADGATE_FILLBOOST"
#define SPP_BWC_ENABLE_GLOBAL_GSP 1
#define SPP_BWC_ENABLE_TIERED_GLOBAL 1
#define SPP_BWC_ENABLE_SIG_UTIL 0
#define SPP_BWC_ENABLE_HEADGATE 1
// There are at most 64 blocks in a 4 KiB page, so this keeps every same-page
// candidate eligible and avoids the normal head/tail drop behavior.
#define SPP_BWC_HEADGATE_KEEP_CANDIDATES 64
#define SPP_BWC_ENABLE_HEADGATE_STREAMING_BOOST 1
#define SPP_BWC_HEADGATE_STREAMING_BOOST_PF_THRESHOLD 25
#define SPP_BWC_HEADGATE_STREAMING_BOOST_FILL_THRESHOLD 75
#define SPP_BWC_HEADGATE_STREAMING_BOOST_ISSUE_PERIOD 1
#define spp_bwc spp_gsp_headgate_fillboost
#include "../spp_bwc/spp_bwc.h"
#undef spp_bwc
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_ISSUE_PERIOD
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_FILL_THRESHOLD
#undef SPP_BWC_HEADGATE_STREAMING_BOOST_PF_THRESHOLD
#undef SPP_BWC_ENABLE_HEADGATE_STREAMING_BOOST
#undef SPP_BWC_HEADGATE_KEEP_CANDIDATES
#undef SPP_BWC_ENABLE_HEADGATE
#undef SPP_BWC_ENABLE_SIG_UTIL
#undef SPP_BWC_ENABLE_TIERED_GLOBAL
#undef SPP_BWC_ENABLE_GLOBAL_GSP
#undef SPP_BWC_VARIANT_TAG

#ifdef SPP_GSP_HEADGATE_FILLBOOST_RESTORE_SPP_BWC_H
#define SPP_BWC_H
#undef SPP_GSP_HEADGATE_FILLBOOST_RESTORE_SPP_BWC_H
#else
#undef SPP_BWC_H
#endif

#endif
